server:
  port: 8088
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
#mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: cn.zfy.behalf.mapper
#spring
spring:
  #datasource mysql config
  datasource:
    username: root
    password: mysqlroot
    url: jdbc:mysql://localhost:3306/behalf?serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.jdbc.Driver
  #redis config
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 300